server:
  port: 8888
logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kapilkanur/x-config-server
          clone-on-start: true
    fail-fast: true
management:
  endpoints:
    web:
      exposure:
        include: health,info